# Generated by Django 5.2.1 on 2025-07-27 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Toplam Tutar')),
                ('kayit_durumu', models.CharField(choices=[('ODEME_BEKLENIYOR', 'Ödeme Bekleniyor'), ('ONAY_BEKLENIYOR', 'Kayıt Onayı Bekleniyor'), ('KAYIT_TAMAMLANDI', 'Kayıt Tamamlandı'), ('KAYIT_REDDEDILDI', 'Kayıt Reddedildi')], default='ODEME_BEKLENIYOR', max_length=20, verbose_name='Kayıt Durumu')),
                ('dekont', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='Dekont')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='Kurs')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Veli')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student', verbose_name='Öğrenci')),
            ],
        ),
    ]
