# Generated by Django 5.2.3 on 2025-06-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Toplam Tutar'),
        ),
    ]
