# Generated by Django 5.2.3 on 2025-06-19 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SummerProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='YAZINA DEĞER KAT 2025 YAZ OKULLARI', max_length=200, verbose_name='Başlık')),
                ('location', models.CharField(default='İSTANBUL', max_length=100, verbose_name='Konum')),
                ('price', models.DecimalField(decimal_places=2, default=16000.0, max_digits=10, verbose_name='Ücret')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Program mı?')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_and_time', models.CharField(max_length=255, verbose_name='Yer / Saat')),
                ('grade_range', models.CharField(max_length=100, verbose_name='Sınıf Aralığı')),
                ('capacity', models.PositiveIntegerField(default=100, verbose_name='Kontenjan')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='main.summerprogram')),
            ],
        ),
    ]
