# Generated by Django 5.2.3 on 2025-06-19 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('order', models.PositiveIntegerField(default=0, help_text='Bölümlerin gösterileceği sıra (küçükten büyüğe)', verbose_name='Sıralama')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.summerprogram')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
