# Generated by Django 5.2.3 on 2025-06-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_programsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='summerprogram',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Afiş Görseli'),
        ),
    ]
