# Generated by Django 5.2.3 on 2025-06-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_summerprogram_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='summerprogram',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi'),
        ),
    ]
